#!/bin/bash

set -eux

ASSERT_GEM_VERSION=2.7.8

echo "Testing runtime compability"

# shellcheck disable=1091
source "/var/vcap/packages/ruby-2.4-r5/bosh/runtime.env"
ruby -e 'puts "test"'

echo "Testing compile compability"

# shellcheck disable=1091
source "/var/vcap/packages/service/bosh/runtime.env"
cd /var/vcap/packages/service/
ruby server.rb &
sleep 3
curl http://localhost:1234 | grep 'Hello, world!'
kill -9 $!

gems_version=$(bundle exec gem -v)
if [[ $gems_version == *"$ASSERT_GEM_VERSION"* ]]; then
  echo "found correct rubygems version $gems_version"
else
  echo "wrong rubygems version: $gems_version"
  exit 1
fi
